Data Operation 

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel() # number of elements

12

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4)

tensor([[ 0.3629, -0.5019,  0.2671,  1.3792],
        [ 1.8356, -2.1737,  0.7389,  0.8340],
        [ 1.5417,  0.9246, -0.9945,  0.5976]])

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1) # dim=0 means vertical operation, dim=1 means horizontal operation

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
X.sum()

tensor(66.)

In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
a + b # a will be duplicated first to [0] [0]
#                                     [1] [1]
#                                     [2] [2]
# then, b will be duplicated to [0] [1]
#                               [0] [1]
#                               [0] [1]
# Broadcasting mechanism

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
X, X[-1], X[1:3] # [-1] chooses the last element, while [1:3] chooses the second and third elements

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
X[1, 2] = 9 # [column index, row index]
#   [0, 1, 2, 3]
#[0]
#[1]       9
#[2]
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [22]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [23]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140564354092144
id(Z): 140564354092144


In [24]:
before = id(X)
X += Y
id(X) == before

True

In [25]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [26]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [28]:
# Test
a = torch.tensor([1.0]) # scalar 0-d
b = torch.tensor([1.0, 2.7, 3.4]) # vector 1-d
c = torch.tensor([[1.0, 2.7, 3.4], [5.0, 0.2, 4.6], [4.3, 8.5, 0.2]]) # matrix 2-d
a, b, c

(tensor([1.]),
 tensor([1.0000, 2.7000, 3.4000]),
 tensor([[1.0000, 2.7000, 3.4000],
         [5.0000, 0.2000, 4.6000],
         [4.3000, 8.5000, 0.2000]]))

In [29]:
Z = torch.arange(16).reshape((4, 4))
Z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [30]:
Z[1, 2]

tensor(6)

In [31]:
Z[1, :]

tensor([4, 5, 6, 7])

In [32]:
Z[:, 1]

tensor([ 1,  5,  9, 13])

In [33]:
Z[1:3, 1:]

tensor([[ 5,  6,  7],
        [ 9, 10, 11]])

In [34]:
Z[::3, ::2]

tensor([[ 0,  2],
        [12, 14]])

In [ ]:
"""
index =     [0] [1] [2] [3]
[0]        [[ 0,  1,  2,  3],
[1]        [ 4,  5,  6,  7],
[2]        [ 8,  9, 10, 11],
[3]        [12, 13, 14, 15]]
"""