Data Pre-processing

In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [3]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [4]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print("inputs = \n" + str(inputs))
print("outputs = \n" + str(outputs))
# inputs = inputs.fillna(inputs.mean())
# print(inputs.mean())
# inputs = inputs.fillna(3)
print(inputs.loc)

inputs['NumRooms'] = pd.to_numeric(inputs['NumRooms'], errors='coerce') # Converting 'NumRooms' column to numeric
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean()) # Filling NaNs with the mean

print(inputs)

inputs = 
   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
outputs = 
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [ ]:
print(inputs)
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [6]:
inputs, outputs, inputs.values, outputs.values

(   NumRooms  Alley_Pave  Alley_nan
 0       3.0        True      False
 1       2.0       False       True
 2       4.0       False       True
 3       3.0       False       True,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64,
 array([[3.0, True, False],
        [2.0, False, True],
        [4.0, False, True],
        [3.0, False, True]], dtype=object),
 array([127500, 106000, 178100, 140000]))

In [16]:
import torch

print(inputs.values)
print(outputs.values)

print(inputs.values.dtype)
print(outputs.values.dtype)

# inputs.values.astype(float)

df = pd.DataFrame(inputs.values) # Converting object to data frame

df = df.replace({True: 1, False: 0}).astype(float) # Replacing True and False to 1 and 0, then converting the type to float

dt = df.to_numpy() # Converting data frame to numpy array

print(dt)
print(dt.dtype)

# X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)

X, y = torch.tensor(dt), torch.tensor(outputs.values)

print(X)
print(y)

[[3.0 True False]
 [2.0 False True]
 [4.0 False True]
 [3.0 False True]]
[127500 106000 178100 140000]
object
int64
[[3. 1. 0.]
 [2. 0. 1.]
 [4. 0. 1.]
 [3. 0. 1.]]
float64
tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500, 106000, 178100, 140000])
