Custom Layer

In [1]:
import torch
import torch.nn.functional as F 
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()
    
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer()
)
Y = net(torch.rand(4, 8))
Y.mean()

tensor(9.3132e-10, grad_fn=<MeanBackward0>)

In [3]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.7468,  0.9449, -0.9173],
        [ 0.0247,  0.2326, -1.1419],
        [-1.3055,  0.6305,  0.2722],
        [ 0.1842, -0.2218, -0.3146],
        [ 0.5338,  0.9427,  0.6207]], requires_grad=True)

In [4]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.6963, 0.0000],
        [0.4510, 0.4078, 0.0000]])

In [5]:
net = nn.Sequential(
    MyLinear(64, 8),
    MyLinear(8, 1)
)
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])